### PR TITLE
[TypeGenerator] Use relative fragment reference imports.

### PR DESCRIPTION
**Pull request by alloy**
Alrighty, this works perfectly ✨

### CODE REVIEW

**Comment by alloy** [comment]
Oh wait, need to add the babel config to the example app.

**Comment by alloy** [comment]
Found a last little bug in the babel plugin related to relative imports.

**Comment by kastermester** [comment]
Let me know if you need help with it :) Otherwise I'll continue working on this transformer :)

**Comment by alloy** [comment]
Got it already :)

https://github.com/alloy/relay/pull/5/commits/11c29b2963ffb41f45e3375895ecd6397e319f4a

**Comment by alloy** [comment]
Alright, actually done now. With this in I feel comfortable opening a PR on the Relay repo.

**Comment by kastermester** [comment]
LGTM!

**Pull request merged**
